### ISSUE TITLE
Empty table header

### ISSUE THREAD

**Issue by lukebakken** [basho-labs/thumbs#35]
Comments added by thumbs have an empty table header:

```
|||||
------------ | -------------|------------ | ------------- | -------------
add_thumbs d7a0c20 | :arrow_right: | develop 2a1e565 | :white_check_mark: completed
```

**Comment by davidx** [comment]
This issue popped up overnight, should be addressed by:  https://github.com/basho-labs/thumbs/pull/41

**Comment by davidx** [comment]
I conflated the 2 issues:
1. overnight, due to GitHub UI upgrade, certain markdown behaves differently, this made the markdown for the build status appear unrendered. fix for this has been merged and deployed.
2. The table header appears empty, this is an intentional tradeoff. its seemingly not possible to have a table row without a header, apparantly, hence the empty one. @sanmiguel figured out that you can just make a table header only however that significantly increases the boldness of the text, which is still being debated by the ux department.

**Comment by davidx** [comment]
Going to go ahead and close this as a wontfix. limitations of current GitHub comment markdown vs needed result.
